### PR TITLE
Added Do good section below Joy section

### PR DESCRIPTION
**Pull request by REEKRAJROY**

### CODE REVIEW

**Comment by nileshtrivedi** [comment]
@REEKRAJROY Hey, thanks for submitting this.

Have you looked at #240? Will you be able to fix the remaining enhancements from there? If yes, this will be ready for public release.

**Comment by REEKRAJROY** [comment]
@nileshtrivedi I saw that the slider has already been implemented and the site is responsive for small screens. Can you kindly mention what exact colors and text formatting will be required? I can then try to implement exactly those.

**Comment by nileshtrivedi** [comment]
The slider needs to be persistent. Once the user moves it, and closes the tab, after re-opening it, the value should be read from localStorage. The idea is that slider acts like a reminder for your life stage - which helps you plan what to prioritize.

Text formatting will be same as existing sections, and you can pick some light color that's different from existing 5 sections.

**Comment by REEKRAJROY** [comment]
Ok, I understand. I will try to implement the same.

**Review by nileshtrivedi — APPROVED** [review]

**Pull request merged**
